### ISSUE TITLE
HTTP Error Occurs When Downloading Process Data

### ISSUE THREAD

**Issue by BlueCat-de** [ermongroup/SDEdit#28]
It seems that the url for processed data is no longer usable:

> ERROR - main.py - 2023-12-11 10:45:23,843 - Traceback (most recent call last):
>   File "/home/chenqm/projects/cross-domain-trajectory-editing-private/SDEdit/main.py", line 104, in main
>     runner.image_editing_sample()
>   File "/home/chenqm/projects/cross-domain-trajectory-editing-private/SDEdit/runners/image_editing.py", line 102, in image_editing_sample
>     download_process_data(path="colab_demo")
>   File "/home/chenqm/projects/cross-domain-trajectory-editing-private/SDEdit/functions/process_data.py", line 8, in download_process_data
>     torch.hub.download_url_to_file('https://image-editing-test-12345.s3-us-west-2.amazonaws.com/colab_examples/lsun_bedroom1.pth', os.path.join(path, 'lsun_bedroom1.pth'))
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/site-packages/torch/hub.py", line 621, in download_url_to_file
>     u = urlopen(req)
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 523, in open
>     response = meth(req, response)
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 632, in http_response
>     response = self.parent.error(
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 561, in error
>     return self._call_chain(*args)
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 494, in _call_chain
>     result = func(*args)
>   File "/home/chenqm/anaconda3/envs/jax_diffuser/lib/python3.9/urllib/request.py", line 641, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden

![image](https://github.com/ermongroup/SDEdit/assets/72798894/0833c43e-28b9-4277-93c0-f61ce552f25b)

**Comment by Powerofev1l** [comment]
i met the same problem with u,have u solved it?

**Comment by wentaohu1208** [comment]
the same problem

**Comment by sunmoumou1** [comment]
me too

**Comment by hotpot-killer** [comment]
same problem

**Comment by jzhangCSER01** [comment]
same problem

**Comment by BUAACY** [comment]
same problem

**Comment by tiantian095** [comment]
how to solve it

**Comment by QuBohao** [comment]
same problem，how to solve it

**Comment by zzkkzz** [comment]
You can use Xunlei to download

**Comment by QuBohao** [comment]
> You can use Xunlei to download

Thank you for your response, but the link is invalid, Xunlei also can not download the data.

**Comment by Xueting-Bi** [comment]
Why hasn't anyone answered

**Comment by fanfanffff1** [comment]
same problem
